import "../styles/globals.css";
import type { Metadata } from "next";
import Providers from "@/components/providers";

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
  icons: {
    icon: {
      url: "/favicon.png",
      href: "/favicon.png",
    },
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className="scroller h-full" lang="en">
      <Providers>
        <body className="flex h-dvh min-h-full flex-col bg-zinc-950">
          {children}
        </body>
      </Providers>
    </html>
  );
}
