import Header from "@/components/layout/header";
import "../styles/globals.css";
import type { Metadata } from "next";
import Footer from "@/components/layout/footer";
import { Suspense } from "react";
import Loading from "./loading";
import Providers from "@/components/providers";

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className="scroller h-full" lang="en">
      <Providers>
        <body className="flex flex-col min-h-full h-dvh font-kanit bg-slate-950">
          <Header />
          <Suspense fallback={<Loading />}>
            <main className="flex-1 basis-auto">{children}</main>
          </Suspense>
          <Footer />
        </body>
      </Providers>
    </html>
  );
}
